project:
    type: default
    output-dir: docs

lang: de
toc: false
toc-depth: 5
toc-location: right
toc-expand: true
number-sections: false
appendix-style: default
  
format:
    html:
        page-layout: full
        theme: 
          - brand
          - _style/_custom.scss
        # css: _style/_style.css
        # include-in-header: _includes/_in_header.html
        # include-after-body: _includes/_after_body.html
        embed-resources: false
        self-contained-math: false

engine: knitr
brand: _brand.yml
    